/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AuthLayoutRouteImport } from './routes/_auth/layout'
import { Route as OnboardingLayoutRouteImport } from './routes/_onboarding/layout'
import { Route as AppSettingsLayoutRouteImport } from './routes/_app/settings/layout'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AuthSignInIndexRouteImport } from './routes/_auth/sign-in/index'
import { Route as AuthSignUpIndexRouteImport } from './routes/_auth/sign-up/index'
import { Route as OnboardingOnboardingIndexRouteImport } from './routes/_onboarding/onboarding/index'
import { Route as AppSettingsProfileIndexRouteImport } from './routes/_app/settings/profile/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLayoutRoute = OnboardingLayoutRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsLayoutRoute = AppSettingsLayoutRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const OnboardingOnboardingIndexRoute =
  OnboardingOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => OnboardingLayoutRoute,
  } as any)
const AppSettingsProfileIndexRoute = AppSettingsProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppSettingsLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AppSettingsLayoutRouteWithChildren
  '/dashboard/': typeof AppDashboardIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/sign-in/': typeof AuthSignInIndexRoute
  '/sign-up/': typeof AuthSignUpIndexRoute
  '/onboarding/': typeof OnboardingOnboardingIndexRoute
  '/settings/profile/': typeof AppSettingsProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof AppSettingsLayoutRouteWithChildren
  '/dashboard': typeof AppDashboardIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/onboarding': typeof OnboardingOnboardingIndexRoute
  '/settings/profile': typeof AppSettingsProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_onboarding': typeof OnboardingLayoutRouteWithChildren
  '/_app/settings': typeof AppSettingsLayoutRouteWithChildren
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_onboarding/onboarding/': typeof OnboardingOnboardingIndexRoute
  '/_app/settings/profile/': typeof AppSettingsProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/dashboard/'
    | '/users/'
    | '/sign-in/'
    | '/sign-up/'
    | '/onboarding/'
    | '/settings/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/dashboard'
    | '/users'
    | '/sign-in'
    | '/sign-up'
    | '/onboarding'
    | '/settings/profile'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_onboarding'
    | '/_app/settings'
    | '/_app/dashboard/'
    | '/_app/users/'
    | '/_auth/sign-in/'
    | '/_auth/sign-up/'
    | '/_onboarding/onboarding/'
    | '/_app/settings/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  OnboardingLayoutRoute: typeof OnboardingLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_onboarding/onboarding/': {
      id: '/_onboarding/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingOnboardingIndexRouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
    '/_app/settings/profile/': {
      id: '/_app/settings/profile/'
      path: '/profile'
      fullPath: '/settings/profile/'
      preLoaderRoute: typeof AppSettingsProfileIndexRouteImport
      parentRoute: typeof AppSettingsLayoutRoute
    }
  }
}

interface AppSettingsLayoutRouteChildren {
  AppSettingsProfileIndexRoute: typeof AppSettingsProfileIndexRoute
}

const AppSettingsLayoutRouteChildren: AppSettingsLayoutRouteChildren = {
  AppSettingsProfileIndexRoute: AppSettingsProfileIndexRoute,
}

const AppSettingsLayoutRouteWithChildren =
  AppSettingsLayoutRoute._addFileChildren(AppSettingsLayoutRouteChildren)

interface AppLayoutRouteChildren {
  AppSettingsLayoutRoute: typeof AppSettingsLayoutRouteWithChildren
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppSettingsLayoutRoute: AppSettingsLayoutRouteWithChildren,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface OnboardingLayoutRouteChildren {
  OnboardingOnboardingIndexRoute: typeof OnboardingOnboardingIndexRoute
}

const OnboardingLayoutRouteChildren: OnboardingLayoutRouteChildren = {
  OnboardingOnboardingIndexRoute: OnboardingOnboardingIndexRoute,
}

const OnboardingLayoutRouteWithChildren =
  OnboardingLayoutRoute._addFileChildren(OnboardingLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  OnboardingLayoutRoute: OnboardingLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
